### ISSUE TITLE
default= in .add_argument() always overrides config-file value

### ISSUE THREAD

**Issue by timvaillancourt** [kampka/yconf#2]
Hey guys, thanks for yconf.

When I use it with 'default=' options to .add_argument(), everything works as-expected until I provide yconf a config file with -c/--config. When my config file has a non-default value it always is ignored. I'd prefer that the argument default= flag is used only if the config file didn't define a value, not command-line only.

An example yml:

```
production:
  db:
    port: 27018
```

The .add_argument() for 'db.port':

```
parser.add_argument("-P", "-db.port", dest="db.port", help="DB Port", type=int, default=27017)
```

When I run a script that simply prints the value for 'db.port', the 27017 default (or whatever I set on the command line) always wins and never a value in the config file:

```
$ python test.py -e production -c test.yml 
27017
```

Is there a way to have default values that only get applied if BOTH the command-line and config-file has not defined it?

Thanks!

Tim

**Comment by kampka** [comment]
Thanks for reporting this.
I pushed a fix, if you can verify it's working for you as expected I'll release a new version.

**Comment by timvaillancourt** [comment]
@kampka: this is now working exactly as expected. Thanks so much for the quick response!
