### ISSUE TITLE
New release number/Re-push 0.3.3 to PyPi?

### ISSUE THREAD

**Issue by timvaillancourt** [kampka/yconf#5]
Hello,

I have have a project that depends on the fix in this commit https://github.com/kampka/yconf/commit/e468a2c52f7d4208a73a19c14cdeb8bbe1b62738.

This project depends on requirements.txt and pex but I think the 0.3.3 version PyPi doesn't have this fix. Both pex and pip don't want to play nice with "Editable Releases" that point to a github commit so I'm stuck.

Is it possible to re-push 0.3.3 or create a 0.3.4 version?

Thanks!

**Comment by kampka** [comment]
I released version 0.3.4 and uploaded a new source dist to pypi.

If you still feel like the fix in e468a2c52f7d4208a73a19c14cdeb8bbe1b62738 is not working for you, please file a new bug that describes the issue you are facing.

**Comment by timvaillancourt** [comment]
It's working wonderfully. Thanks @kampka!
